baseURL = "https://www.telemetryjet.com/"
languageCode = "en-us"
title = "The ultimate data platform for hardware projects."
theme = "tjet-website-theme"
sectionPagesMenu = "main"
pluralizelisttitles = false

[params]
    version = "v0.1.0"
    siteUrl = "https://www.telemetryjet.com"
    docsUrl = "https://docs.telemetryjet.com"
    filesUrl = "https://files.telemetryjet.com"
    cloudUrl = "https://app.telemetryjet.com"
    description = "TelemetryJet - The ultimate data platform for hardware projects."
    author = "TelemetryJet Team, telemetryjet@gmail.com"
    
[taxonomies]

[markup.goldmark.renderer]
unsafe = true